services:
  pgvector_service:
    image: phidata/pgvector:16
    container_name: pgvector_container
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - "./.env"
    depends_on:
      - pgvector_service
    network_mode: "host"
