name: Build .deb and snap
'on':
  push:
    branches:
      - main
jobs:
  build_deb_snap:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Make app
        working-directory: ./client 
        run: make
      - name: Find version
        working-directory: ./client
        run: echo "VERSION=$(cat control | grep Version | cut -d' ' -f2)" >> $GITHUB_ENV
      - name: Create deb directory structure
        working-directory: ./client
        run: |
          mkdir ishell_${VERSION}_amd64;
          mkdir -p ishell_${VERSION}_amd64/usr/bin;
          mkdir ishell_${VERSION}_amd64/DEBIAN
      - name: Copy files
        working-directory: ./client
        run: |
          cp ishell ishell_${VERSION}_amd64/usr/bin/;
          cp control ishell_${VERSION}_amd64/DEBIAN/
      - name: Build deb
        working-directory: ./client
        run: dpkg --build ishell_${VERSION}_amd64/

      - name: Create snap file
        uses: snapcore/action-build@v1
        with:
          path: ./client
          
      - name: Import Debian repository GPG key
        run: echo "${{ secrets.GPG_KEY }}" | gpg --import
          
      - name: Fetch Debian repository
        uses: actions/checkout@v4
        with:
          repository: 'smart-linux-shell/deb'
          path: 'deb-repo'
          ssh-key: ${{ secrets.SSH_KEY }}
        
      - name: Replace with new version
        run: |
          rm deb-repo/*.deb;
          cp client/ishell_${VERSION}_amd64.deb deb-repo/
          
      - name: Create Packages and Packages.gz
        working-directory: deb-repo
        run: |
          dpkg-scanpackages --multiversion . > Packages;
          gzip -k -f Packages
          
      - name: Create Release, Release.gpg and InRelease
        working-directory: deb-repo
        run: |
          apt-ftparchive release . > Release;
          gpg --default-key "ishell" -abs -o - Release > Release.gpg;
          gpg --default-key "ishell" --clearsign -o - Release > InRelease
          
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./deb-repo
