name: Build and push docker image to Docker Hub

on:
  workflow_run:
    workflows: [Build_package]  
    types:
      - completed
    branches:
      - 'main'
      - 'stage'
      - 'cicd-workflow'
      - 'integration'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download deb artifacts
        uses: actions/download-artifact@v3
        with:
          name: deb-packages
          path: pkg/deb

      - name: Push to Docker Hub
        uses: smart-linux-shell/workflows@main
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          cicd-github-token: ${{ secrets.CICD_GITHUB_TOKEN }}
